apiVersion: apps/v1
kind: Deployment
metadata:
  name: castlemock-deployment
spec:
  selector:
    matchLabels:
      app: castlemock
  template:
    metadata:
      labels:
        app: castlemock
    spec:
      containers:
      - name: castlemock
        image: castlemock/castlemock
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: castlemock-service
spec:
  type: NodePort 
  selector:
    app: castlemock
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
